# Travis configuration for building Xapian. This is
# fairly intensive, so we only enable it for pull
# requests.
#
# Right now, we build on containerised linux, which
# travis provides as Ubuntu 12.04 LTS so we have to
# upgrade a lot of stuff to get something vaguely
# modern.
sudo: false
language: cpp
env:
  global:
    # Tell bootstrap where to clone ./common from
    - XAPIAN_COMMON_CLONE_URL=https://github.com/xapian/xapian.git
matrix:
  include:
    - compiler: gcc
      os: linux
      # GCC we want v4.9.
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - doxygen
            - graphviz
            - help2man
            - python-docutils
            - pngcrush
            - python-sphinx
            - uuid-dev
            - libpcre3-dev
            - libmagic-dev
            - tcl
            - libsvm-dev
            - gcc-4.9
            - g++-4.9
      # Installing it isn't enough!
      env: USE_CC=gcc-4.9 USE_CXX=g++-4.9
    - compiler: clang
      os: linux
      # Clang is already installed, but we want to build using the
      # llvm c++ library, not the GCC one. (Otherwise, depending on
      # the GCC version, there can be issues.)
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - doxygen
            - graphviz
            - help2man
            - python-docutils
            - pngcrush
            - python-sphinx
            - uuid-dev
            - libpcre3-dev
            - libmagic-dev
            - tcl
            - libsvm-dev
            - libc++-dev
      # We also have to disable an error, because (older?)
      # perl header files don't play nicely with clang.
      env: USE_CC=clang USE_CXX='clang++ -stdlib=libc++' CXXFLAGS=-Wno-error=reserved-user-defined-literal
    - os: osx
      before_install:
        - brew update
        - brew install doxygen help2man graphviz pngcrush libmagic pcre libsvm
        - pip install sphinx docutils
      env: CXXFLAGS=-Wno-error=reserved-user-defined-literal

before_script:
  # Bootstrap everything (including letor, which isn't done
  # by default), then configure using our chosen compiler.
  - ./bootstrap xapian-core xapian-applications/omega swig xapian-bindings xapian-letor
  - ./configure CC="$USE_CC" CXX="$USE_CXX"
script: make && make check VERBOSE=1 AUTOMATED_TESTING=1
